### ISSUE TITLE
What is the newest version of the YouTube app is compatible with YouPiP v1.2.2?

### ISSUE THREAD

**Issue by calvincorrieri** [PoomSmart/YouPiP#10]
Can you please include the version(s) of the YouTube app that each release is compatible with? It would make it much easier to figure out than just finding a bunch of posts saying “X tweak works with the newest version of YouTube” but that’s from three months ago so it’s no help. I’m getting off track, sorry. I’d just really appreciate (and I know others would to) if you put the YouTube app versions in each new releases patch notes (and possibly the last few versions too)

**Comment by PoomSmart** [comment]
![image](https://user-images.githubusercontent.com/3608783/121767441-6f64dc00-cb82-11eb-88a6-3951bf9fb198.png)

0.0.8: 15.47
0.0.9: 16.17
0.0.11 - 1.2.1: 16.17+
1.2.2: 15.22.4+

**Comment by calvincorrieri** [comment]
Thank you 🙏

**Comment by PoomSmart** [comment]
Changelogs annotated.
