### ISSUE TITLE
PiP breaks when setting a playback speed

### ISSUE THREAD

**Issue by nicknitewolf** [PoomSmart/YouPiP#12]
Steps to reproduce:
1. Use the 'Start PiP automatically' setting
2. Set playback to other than 1x (0.25x, 0.5x, 0.75x, 1.25x, 1.5x, 2x)
3. Swipe to home (to start PiP)
4. PiP video will either stop playing the video, jitter a lot, or audio cuts intermittently

Seems to be happening most of the time but works perfectly sometimes.

**Comment by PoomSmart** [comment]
How is it with version 1.3.0?

**Comment by nicknitewolf** [comment]
I’m not sure if I’m understanding what your latest patch does. Do I have to enable legacy pip?

**Comment by PoomSmart** [comment]
Yes, well. Just to see if the legacy PiP addresses your issue, while the main issue here, is iOS itself and not YouPiP.

**Comment by nicknitewolf** [comment]
Very odd. Honestly I'd wait for apple to update avkit to fix the issue since I'm currently running ios 15 sideloaded (which will not trigger compat mode)

**Comment by nicknitewolf** [comment]
Wait compatibility mode is enabled by default right? https://github.com/PoomSmart/YouPiP/blob/main/Compat.xm#L9
So the sideloaded version will have it enabled?

**Comment by nicknitewolf** [comment]
nvm this should do it https://github.com/nicknitewolf/YouPiP/commit/381f5149c673b03531f73c7f069462ac4562a2f4

**Comment by nicknitewolf** [comment]
My bad https://github.com/nicknitewolf/YouPiP/commit/5e58023432eb37229ab845f74f54265965154e6b

**Comment by nicknitewolf** [comment]
Yep legacy pip works perfectly. Sucks that it breaks ytuhd
