### ISSUE TITLE
PiP While The Device Is Locked:

### ISSUE THREAD

**Issue by shayshtern** [PoomSmart/YouPiP#13]
Can you add this option to keep it play while the device is locked or on the lock screen?

Thank you.

**Comment by nicknitewolf** [comment]
This doesn’t seem like its possible. Default iOS behaviour stops PiP playback when screen is locked. (See safari)

**Comment by PoomSmart** [comment]
Potentially out of scope of YouPiP. Think of this as another tweak that forces PiP on the lock screen or something.
