### ISSUE TITLE
PiP crashes when going to the next video.

### ISSUE THREAD

**Issue by qnblackcat** [PoomSmart/YouPiP#15]
**Device Information:**
- iOS Version: iPhone 6s - iOS 14.3.
- Jailbreak type: checkra1n/Substitute (2.1.0).
- YouPiP Version: 1.3.0 (Legacy mode enabled).
- YouTube version: 16.22.5 with AutoPlay is on.
- Active Method: On app dismiss.

**How to reproduce:** The video is too big for Github. I uploaded it here: [Drive](https://drive.google.com/file/d/1V-hKjOXrEWd4guqOsIZ-bkhtr1LN6wA2/view?usp=sharing)

**Note:** It doesn't happen if Legacy mode is disabled.

**Comment by PoomSmart** [comment]
Does this happen on YouTube version 16.23.2 as well?

**Comment by qnblackcat** [comment]
Yes. It does happen on YouTube v16.23.2.

**Comment by PoomSmart** [comment]
As bizarre as it sounds, I have
- iPhone SE (1st gen) iOS 14.6
- checkra1n/Cydia Substrate 0.9.7113
- YouPiP 1.3.1, legacy mode enabled
- YouTube version 16.23.2 with AutoPlay on
- Activation Method: On app dismiss

But I don't face that issue.

**Comment by qnblackcat** [comment]
So it must be tweak conflicts.
I did some tests. Turn out Cercube is the bad guy. I disabled Cercube in YouTube (using Choicy). PiP no longer crashes when going to the next video. 
I use Cercube 5.2.24 from Alfhaily's repo with my Cercube premium account.
Anyways, it is not your fault. Thank you for making YouPiP

**Comment by qnblackcat** [comment]
not related but I got this error while trying to compile YouPiP v1.3.1
![Screen Shot](https://user-images.githubusercontent.com/52943116/121917993-d4295d80-cd5f-11eb-88db-1ed513335219.png)

**Comment by PoomSmart** [comment]
@qnblackcat Pull the latest changes from PSPrefs repo.

**Comment by qnblackcat** [comment]
> So it must be tweak conflicts.
> I did some tests. Turn out Cercube is the bad guy. I disabled Cercube in YouTube (using Choicy). PiP no longer crashes when going to the next video.
> I use Cercube 5.2.24 from Alfhaily's repo with my Cercube premium account.
> Anyways, it is not your fault. Thank you for making YouPiP
> 
> Edit: tested with YouPiP 1.3.1

More specific: PiP will not crash if I don't use Cercube Default Quality.

**Comment by qnblackcat** [comment]
@PoomSmart 
Info:
- iOS 14.3 / Substitute
- YouTube 16.25.2
- Cercube 5.2.26. Default quality **enabled**.
- YouPiP 1.4.4
- Legacy PiP **disabled** 
- Sample Buffer Hack **enabled**

=> With Sample Buffer Hack enabled & Cercube default quality enabled, PiP crashes when going to the next video. It doesn't happen with YouPiP v1.4.3

**Comment by PoomSmart** [comment]
@qnblackcat That's very unexpected based on the changes I have made. By the way, by "crashes", does that mean the app crashes?

**Comment by qnblackcat** [comment]
> @qnblackcat That's very unexpected based on the changes I have made. By the way, by "crashes", does that mean the app crashes?

Only PiP crashes. The app was fine!

https://user-images.githubusercontent.com/52943116/124151815-2804a800-dabd-11eb-8ea5-f2f986c7908f.mov

**Comment by PoomSmart** [comment]
And, what exactly do you mean by "Cercube Default quality enabled" ?

**Comment by qnblackcat** [comment]
I mean the default quality on Wifi / Celullar in Cercube's settings.
![IMG_1316](https://user-images.githubusercontent.com/52943116/124152466-c133be80-dabd-11eb-9c0f-7aedd560ff80.jpg)

**Comment by PoomSmart** [comment]
@qnblackcat How does it look with YouPiP 1.4.5?

**Comment by qnblackcat** [comment]
@PoomSmart No more crashes but the speed-up happened again

**Comment by PoomSmart** [comment]
The speedup bug is even an issue on iOS 15 but now that there's no more crashing I will close this issue. If you think the speedup bug is really because of YouPiP then please file a new issue.
