### ISSUE TITLE
Crashes when using button PIP, and No pip in legacy mode

### ISSUE THREAD

**Issue by Logs22** [PoomSmart/YouPiP#18]
iPad OS 14.3, YT 16.23.3, YouPiP 1.3.1, 6th gen iPad, Odysseyra1n

Hi, I've had this issue with changing the mode from dismiss to click for a while now map but haven't gotten around to submitting a bug report. (Sorry about that) here is a log with that issue

https://pastebin.com/5RaRehz0

The other issue, when using legacy mode, pip does not activate for me. Reading the description it sounds like I meet the requirements and that it should work, but it doesn't. I hope this helps, and if you need anything else please let me know.

Also - the only other YouTube tweak installed is YouTopia, but I have recreated these issues with only YouPIP.

**Comment by PoomSmart** [comment]
@Logs22 Could you test this version of YouPiP?
[com.ps.youpip_1.3.2_iphoneos-arm.deb.zip](https://github.com/PoomSmart/YouPiP/files/6662750/com.ps.youpip_1.3.2_iphoneos-arm.deb.zip)

**Comment by Logs22** [comment]
> @Logs22 Could you test this version of YouPiP?
> 
> [com.ps.youpip_1.3.2_iphoneos-arm.deb.zip](https://github.com/PoomSmart/YouPiP/files/6662750/com.ps.youpip_1.3.2_iphoneos-arm.deb.zip)
> 
> 

That fixed both issues!

**Comment by PoomSmart** [comment]
@Logs22 May I ask were there any other YouTube tweaks when YouTube was crashing?

**Comment by Logs22** [comment]
> @Logs22 May I ask were there any other YouTube tweaks when YouTube was crashing?

I did have Youtopia, but I tested with YouTube completely stock as well and only YouPIP and still had crashing

**Comment by PoomSmart** [comment]
Ok, bizarre.
