### ISSUE TITLE
Show YouTube’s default PiP

### ISSUE THREAD

**Issue by nicknitewolf** [PoomSmart/YouPiP#19]
It seems like YouTube has announced official support for PiP. Not sure if it’s possible to force enable it as the option has shown up for some people.

https://imgur.com/a/cf2pTuM

**Comment by PoomSmart** [comment]
Do you know what YouTube version is that?

**Comment by nicknitewolf** [comment]
> Do you know what YouTube version is that?

16.23.3, but it seems like google is A/B testing it cos the menu disappears when I restart the app.

**Comment by PoomSmart** [comment]
Done as of 1.3.4
