### ISSUE TITLE
Crashes Youtube App shortly after opening

### ISSUE THREAD

**Issue by ryannair05** [PoomSmart/YouPIP#2]
Device: iPhone 11 Pro Max, iOS 13.5
Bundle version: 16.19.6

Exception type: NSInvalidArgumentException
Reason: -[YTPlayerPIPController initWithPlayerView:delegate:]: unrecognized selector sent to instance 0x28328bf40

Note: This issue can not be reproduced on iOS 14+

**Comment by PoomSmart** [comment]
Fixed, but it is a known issue that native PiP doesn't work yet on iOS 13 and lower. Check `Compat.xm` for development progress.
