### ISSUE TITLE
Background Playback breaks

### ISSUE THREAD

**Issue by nicknitewolf** [PoomSmart/YouPiP#21]
Trying to continue background playback (from control centre) after closing PiP breaks audio stream

iOS 15b2
Using Modern PiP
YouPiP 1.4.1

**Comment by nicknitewolf** [comment]
https://user-images.githubusercontent.com/6513413/123552593-6d696280-d7a9-11eb-97e4-bd4517f705b2.MOV

**Comment by PoomSmart** [comment]
Crash log? YouTube version?

**Comment by nicknitewolf** [comment]
> Crash log? YouTube version?

Doesn’t seem to have a crash log. Its on YouTube 16.24.2

**Comment by PoomSmart** [comment]
@nicknitewolf Can you try YouPiP 1.4.2?

**Comment by nicknitewolf** [comment]
> @nicknitewolf Can you try YouPiP 1.4.2?

Still the same.

**Comment by PoomSmart** [comment]
@nicknitewolf and does YouPiP 1.3.4 work for you?

**Comment by nicknitewolf** [comment]
> @nicknitewolf Does YouPiP 1.3.4 or 1.4.0 work for you? Also, does this happen to every video?

1.3.4 works but sometimes it will trigger the bug. It happens more consistently with 1.4.0 with all videos. Could it be a conflict with Cercube?

**Comment by nicknitewolf** [comment]
Happens as well on iOS 14 on 1.4.2

**Comment by PoomSmart** [comment]
@nicknitewolf How does it look with YouPiP 1.4.5?

**Comment by nicknitewolf** [comment]
Does not work still. I suspect that I have triggered the speed up bug again with the SampleBufferCompat. Please refer to the video below:

https://user-images.githubusercontent.com/6513413/124347073-06b6cf80-dc15-11eb-9c43-b14c108ef773.MOV
