### ISSUE TITLE
ADD: YouTube System theme Appearance use Device Theme

### ISSUE THREAD

**Issue by gh0sti** [PoomSmart/YouPiP#25]
As of yesterday using cercube 5.2.26/youtube 16.27.3 YouTube popped up a notification that I could have theme change based on device theme. Light mode/dark mode could be enabled automatically based on if my device was in that mode. 
However this morning that feature disappeared. 

Is it possible similar to how the native PiP feature is being forced on can we also have System theme enabled with a flag?

**Comment by PoomSmart** [comment]
```
%hook YTColdConfig

- (bool)shouldUseAppThemeSetting {
    return true;
}

%end
```

YTSystemAppearance tweak.

**Comment by gh0sti** [comment]
thanks appreciate it
