### ISSUE TITLE
Not an issue 

### ISSUE THREAD

**Issue by 3xtc** [PoomSmart/YouPiP#27]
![B6D0E908-C75A-4DF9-A3DD-50F44540449C](https://user-images.githubusercontent.com/74840505/126931168-b70766f7-0c71-4420-b0b6-daf338a3e27f.jpeg)

**Comment by PoomSmart** [comment]
What?

**Comment by 3xtc** [comment]
> What?

so sorry! thought I typed, where can I find this setting within the code ?

**Comment by PoomSmart** [comment]
It's a native YouTube setting enabled by this portion of code in Tweak.x

```
%hook YTSettingsSectionItemManager

- (YTSettingsSectionItem *)pictureInPictureSectionItem {
    forceEnablePictureInPictureInternal([self valueForKey:@"_hotConfig"]);
    return %orig;
}

%end

```
