### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NguyenASang** [PoomSmart/YouPiP#31]
I have a iphone 6, iOS 12.5.5 
I installed "latest version YouPIP " + "latest YouTube version" but it doesn't working
To make sure that no tweak conflict, I restored my phone then jailbreak and only install this tweak but it still doesn't working
I have a screenshot of the install's detail:

![IMG_0042](https://user-images.githubusercontent.com/87893636/139174629-57d34217-698c-492f-ba90-8595f7698030.PNG)

Can you fix it pls :((
Thank you very much for this useful tweak

**Comment by PoomSmart** [comment]
Update to 1.5.15

**Comment by NguyenASang** [comment]
@PoomSmart Does Youtube Reborn or some such tweak conflict with this tweak?

**Comment by PoomSmart** [comment]
@NguyenASang Not on its own unless YT Reborn does something weird.

**Comment by NguyenASang** [comment]
@PoomSmart Can you explain it more detail, I'm not good at English and "Google Translate" translates something very weird

**Comment by PoomSmart** [comment]
@NguyenASang Let's just say: YouPiP doesn't conflict with YouTube Reborn.

**Comment by NguyenASang** [comment]
@PoomSmart Oh, Thanks but wait me a minute. I still have some questions :))

**Comment by NguyenASang** [comment]
@PoomSmart How about YTReExplore, YTNoShorts, NoInfoYT ?

**Comment by PoomSmart** [comment]
YouPiP conflicts with nothing except for its clones from elsewhere.

**Comment by NguyenASang** [comment]
Okay thanks for reply, I will test it out.

**Comment by NguyenASang** [comment]
No way, it still doesn't work :((
Even using Pip button or using auto Pip 🤔
And still get error when install it:
![IMG_0062](https://user-images.githubusercontent.com/87893636/141244701-c362810e-8c76-46db-a605-014d7b60c316.PNG)
Hope you can fix it.

**Comment by qnblackcat** [comment]
1. The red line in your image, it’s not an error
2. Automatic PiP (native PiP) requires iOS 14.0+

**Comment by NguyenASang** [comment]
How about pip button, it doesn't work

**Comment by NguyenASang** [comment]
@PoomSmart Can you reopen this issue ?

**Comment by NguyenASang** [comment]
@PoomSmart Are you still working on a fix?
