### ISSUE TITLE
Doesn't work on iOS 12.5.5 (more details)

### ISSUE THREAD

**Issue by NguyenASang** [PoomSmart/YouPiP#33]
My iPhone is **iOS 12.5.5** | Jailbreak with **Chimera 1.6.4**

Install this tweak using **Sileo version 2.2.6**
### Install Log:

![IMG_0118](https://user-images.githubusercontent.com/87893636/145152138-b1cc5c38-9014-4d38-8d0c-21ab0137aadd.PNG)

### Video Test: 

https://user-images.githubusercontent.com/87893636/145152715-263cba58-aae6-43a9-9971-1d4c6d431bc4.mp4

### Conflict ???
I see in **[this post](https://www.reddit.com/r/jailbreak/comments/n7zmit/discussion_youpip_and_conflicting_tweaks)** on Reddit say Conflict between YouPiP and Youtube Reborn
**Note:** I tried uninstalling Youtube Reborn, then reinstalling this tweak but **still DOESN'T work**

**Comment by PoomSmart** [comment]
@NguyenASang Can you try reinstalling ForceInPicture?

**Comment by h0rn3z0r** [comment]
> @NguyenASang So, tapping on PiP button doesn't trigger PiP?

@PoomSmart It seems like it depends on the YouTube app version. I tried downgrading and gathered some info which might be useful for your debugging process.

My config is:
iPad Mini 2 (iOS 12.5.1, Chimera 1.6.4)
YouPiP 1.6.0, ForceInPicture 1.0

15.36.2 is the latest working version.
15.37.3 - 15.40.4 (tapping the icon does nothing)
15.41.2 - 15.49.6 (YouPiP prevents playing videos at all, `No stream, tap to retry` error)
16.05.7 and above (tapping the icon does nothing)

**Comment by NguyenASang** [comment]
> 15.36.2 is the latest working version.
I will test it.

**Comment by PoomSmart** [comment]
For the record, I have PiP working just fine on iPhone 5s running iOS 12.5.4, YouTube 16.46.5, jailbroken using unc0ver 6.2.0

**Comment by NguyenASang** [comment]
> @NguyenASang Can you try reinstalling ForceInPicture?

Still not working

**Comment by NguyenASang** [comment]
> For the record, I have PiP working just fine on iPhone 5s running iOS 12.5.4, YouTube 16.46.5, jailbroken using unc0ver 6.2.0 - YouPiP 1.6.0 and ForceInPicture 1.0

@PoomSmart Can you try iOS 12.5.5 ? Maybe this error happened with this iOS version

**Comment by NguyenASang** [comment]
More: now I jailbreak with unc0ver. Not Chimera anymore

**Comment by PoomSmart** [comment]
Ok guys try version 1.6.1 from my repo @NguyenASang @h0rn3z0r

**Comment by h0rn3z0r** [comment]
> Ok guys try version 1.6.1 from my repo @NguyenASang @h0rn3z0r

Works on my side with the latest YouTube

**Comment by NguyenASang** [comment]
@PoomSmart I will test it now :))

**Comment by NguyenASang** [comment]
@PoomSmart IT'S PERFECT THANKS YOU SO MUCH
