### ISSUE TITLE
The button in video (PiP) is quite slow and the menu disappears for too long

### ISSUE THREAD

**Issue by NguyenASang** [PoomSmart/YouPiP#36]
See in the below video:

https://user-images.githubusercontent.com/87893636/146636582-4768ca94-36ee-4b24-a6c4-a3e536cc39f4.mp4

## Read this

As you can see in the video, the menu disappears for too long (and really, I think people don't need that menu to appear when enable the PiP mode, I think it only needs to appears when we click on the video)

Next, the button (such as: pause, play button,...) when I click it takes a while to work (I think it needs to be optimized to work faster)

**Comment by PoomSmart** [comment]
One thing is about the fade timeout of the PiP controls which can't be of YouPiP scope but PiP from everything. The other thing has to do with device performance or YouTube app itself not being properly optimized I would say.

**Comment by NguyenASang** [comment]
@PoomSmart hmm, But Is it necessary the menu to appear when enable the PiP mode (first launch) ?

**Comment by PoomSmart** [comment]
That's for Apple to answer.

**Comment by NguyenASang** [comment]
🤣 Okay close now :)))))
