### ISSUE TITLE
Non-backgroundable PiP bug

### ISSUE THREAD

**Issue by NguyenASang** [PoomSmart/YouPiP#39]
My iPhone is iOS 12.5.5 | Jailbreak with Chimera 1.6.4

Install this tweak using Installer version 5.0.3

**Comment by NguyenASang** [comment]
Sorry for the delay 😅
See in this video:

https://user-images.githubusercontent.com/87893636/156908496-a83fb3f4-9f62-44d0-91f3-fde2d73b5b23.MP4

Expect behavior: Background Pip won't appear when the video is pausing
Actual behavior: Background Pip still appears even the video is pausing

**Comment by PoomSmart** [comment]
This is when non-backgroundable PiP is enabled? If so, that is an expected behavior. The name implies.

**Comment by NguyenASang** [comment]
@PoomSmart Oh, I'm sorry for this misreport 😅
