### ISSUE TITLE
YouTube app hangs

### ISSUE THREAD

**Issue by lgariv** [PoomSmart/YouPIP#4]
I really can't find the reason for it, the logs doesn't show anything useful (unless I overlooked something?), but when I compile the [latest commit](https://github.com/PoomSmart/YouPIP/tree/e94afaaa33ffd7d1795bb260d3a51cbb47ef0d51) and install it on my device, the YouTube app hangs as soon as something starts to play.

Everything works correctly with the [previous commit](https://github.com/PoomSmart/YouPIP/tree/efd4857c2230abc19175188574586d18a21cba1e) tho, so pretty sure it's not a compiler issue.

**Edit:** Unless... it somehow has anything to do with libhooker. More testing needed.

**Comment by PoomSmart** [comment]
Try removing ARC flag in Makefile.

**Comment by lgariv** [comment]
> Try removing ARC flag in Makefile.

That did it. Interesting...
