### ISSUE TITLE
YouPiP makes YouTube crash when trying to play a video.

### ISSUE THREAD

**Issue by mip82324** [PoomSmart/YouPiP#41]
On iOS 12.5.5, when opening YouTube v17.08.2 or any downgraded version, YouPiP crashes the whole app completely when selecting a video.

**Comment by mip82324** [comment]
`<div style="width:100%;height:0px;position:relative;padding-bottom:177.778%;"><iframe src="https://streamable.com/e/sipde3" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>`

**Comment by mip82324** [comment]
https://streamable.com/sipde3

**Comment by PoomSmart** [comment]
Crash log? @mip82324

**Comment by mip82324** [comment]
https://mega.nz/file/S6hFVQCS#1Iu6CdiX7x9-W6eyFceAMe8Ln4TwudC7xDjdJZI_894

**Comment by PoomSmart** [comment]
@mip82324 And no more crashing if YouPiP is disabled or uninstalled?

**Comment by mip82324** [comment]
Yeah I disable it with iCleaner Pro.

**Comment by PoomSmart** [comment]
The crash log you provided doesn't point any direct causes at YouPiP and I can't seem to reproduce on my iPhone 5s iOS 12.5.5 with that exact YouTube version. 😐

**Comment by mip82324** [comment]
Well.. to be honest, it may just be my phone but I'll link a little video understanding, I don't know if this might help but here's a video with YouPiP enabled - https://streamable.com/w9uy7d - and without YouPiP enabled - https://streamable.com/3g2my9
Hope this helps a bit!

**Comment by PoomSmart** [comment]
@mip82324 Try this version (Unzip first the install the deb using Filza)
[com.ps.youpip_1.6.7_iphoneos-arm.deb.zip](https://github.com/PoomSmart/YouPiP/files/8191868/com.ps.youpip_1.6.7_iphoneos-arm.deb.zip)

**Comment by mip82324** [comment]
Works perfectly!! but it doesn't continue after I dismiss it, it disappears when you exit the app.

**Comment by PoomSmart** [comment]
@mip82324 You may want to try installing ForceInPicture or seeing if tapping PiP button on the video overlay works.
