### ISSUE TITLE
Pip button in tab bar doesn't show up

### ISSUE THREAD

**Issue by NguyenASang** [PoomSmart/YouPiP#43]
See in this video:

https://user-images.githubusercontent.com/87893636/156908342-7cd57da2-45ba-4251-a8eb-b7914aa6f889.MP4

**Comment by NguyenASang** [comment]
@PoomSmart I tried to restart YouTube app after enable that option but it sill doesn't work

**Comment by NguyenASang** [comment]
## Detail
The **bug** appears since version _**17.x.x**_
My device: iPhone 6 | iOS 12.5.5
Jailbreak: Chimera

**Comment by NguyenASang** [comment]
@PoomSmart Any update to fix this ?

**Comment by qnblackcat** [comment]
@NguyenASang 
nếu bạn xem lịch sử Pull Request thì sẽ hiểu PoomSmart không thêm tùy chọn đấy mà là người khác thêm (BandarHL), nên bạn nên liên hệ người đó thì đúng hơn. 

Look at the Pull Request, that option was added by BandarHL, you should contact him instead

**Comment by NguyenASang** [comment]
@PoomSmart Fake the version works, it make the PiP in the bar tab display again. That's a smart way, thank you very much.
But one thing, I don't like the new PIP button very much, can you make it a little thicker ? (Just my opinion, the choice is yours)

**Comment by NguyenASang** [comment]
Oh wait, the fake version will stop us from getting new stuffs in YT.
I will keep opening it until it is fixed
