### ISSUE TITLE
YouTube styled YouPiP buttons

### ISSUE THREAD

**Issue by dayanch96** [PoomSmart/YouPiP#45]
Hi. Edited YouPiP icons for better look on bar under player. Hope it be useful.

ZIP: [YouPiP.bundle.zip](https://github.com/PoomSmart/YouPiP/files/8354141/YouPiP.bundle.zip)
Icons:
![yt-pip-tabbar](https://user-images.githubusercontent.com/38832025/160210402-2e4cbfad-8c6f-4d5f-b16d-2b1c782bb3d0.png)
![yt-pip-tabbar@2x](https://user-images.githubusercontent.com/38832025/160210403-f324e7d2-ff3c-4486-abe0-a858ce38d1fe.png)
![yt-pip-tabbar@3x](https://user-images.githubusercontent.com/38832025/160210404-10ea5d29-3f2b-4db2-b576-a7f8157276da.png)

**Comment by PoomSmart** [comment]
Included in 1.6.9
