### ISSUE TITLE
Legacy PiP displays non-toggleable second subtitles.

### ISSUE THREAD

**Issue by Insaneous** [PoomSmart/YouPiP#47]
For some reason when I use Legacy PiP there's subtitles which I can't turn off, if I try to toggle it, it displays another set of subtitles on top of the first ones, which are also smaller. Interestingly, non-toggleable subtitles also carry over to PiP. 
https://imgur.com/a/X9A2PNO/
I have iPhone 12 mini on iOS 14.3 and currently use the latest versions of the app and YouPiP, although this bug persisted for me for several months before. I used non-legacy PiP without this issue but grew tired of speed bug, so I switched back and remembered about the subtitles issue.

**Comment by PoomSmart** [comment]
@Insaneous Any examples videos with that issue?

**Comment by PoomSmart** [comment]
Closed due to inactivity.
