### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by dayanch96** [PoomSmart/YouPiP#48]
Shows error with text pasted below (Lastest PSHeader and YT Headers, ios15 sdk and latest theos, don't know what im doing wrong):

==> Compiling Settings.x (arm64)…
Settings.x:81:9: error: use of undeclared identifier 'kCFCoreFoundationVersionNumber_iOS_15_0'
    if (IS_IOS_BETWEEN_EEX(iOS_14_0, iOS_15_0)) {
        ^
/Users/dan/youpip/../PSHeader/iOSVersions.h:7:152: note: expanded from macro 'IS_IOS_BETWEEN_EEX'
#define IS_IOS_BETWEEN_EEX(start, end) (kCFCoreFoundationVersionNumber >= kCFCoreFoundationVersionNumber_ ## start && kCFCoreFoundationVersionNumber < kCFCoreFoundationVersionNumber_ ## end)

**Comment by PoomSmart** [comment]
What's inside your `$THEOS/vendor/include/version.h` ?

**Comment by dayanch96** [comment]
maximum 14.5

**Comment by dayanch96** [comment]
should this one work? https://github.com/theos/headers/blob/master/version.h

**Comment by dayanch96** [comment]
it worked. tysm for the tip ❤

**Comment by dayanch96** [comment]
also is it ok that YTColorPalette.h not imported in Tweak.x?

**Comment by PoomSmart** [comment]
To update Theos, execute `$THEOS/bin/update-theos`.

**Comment by PoomSmart** [comment]
> also is it ok that YTColorPalette.h not imported in Tweak.x?

Why should it not be?

**Comment by PoomSmart** [comment]
> should this one work? https://github.com/theos/headers/blob/master/version.h

To update Theos, execute `$THEOS/bin/update-theos`.

**Comment by dayanch96** [comment]
> To update Theos, execute `$THEOS/bin/update-theos`

my bad, used `$THEOS/update`

**Comment by dayanch96** [comment]
> > also is it ok that YTColorPalette.h not imported in Tweak.x?
> 
> Why should it not be?

theos keep showing another error:
Tweak.x:154:9: error: use of undeclared identifier 'YTColorPalette'
        YTColorPalette *colorPalette = [_logos_static_class_lookup$YTPageStyleController() currentColorPalette];

as i understand its not YouPiP issue

**Comment by PoomSmart** [comment]
I see. My bad. Fixed in the latest commit of YouPiP.
