### ISSUE TITLE
Youtube crashes when casting video

### ISSUE THREAD

**Issue by BitGrub** [PoomSmart/YouPIP#5]
Here's my log https://pastebin.com/086qC9S6

Can't get around the crash without disabling/uninstalling YouPip

**Comment by lgariv** [comment]
iOS version? YouTube version? Which jailbreak are you using?

**Comment by BitGrub** [comment]
First 5 lines of the log.

Iphone 7, ios14.5.1, checkra1n.

I just updated to the latest youtube app (even though I think updating that app is moronic) and Youtube still crashes when connecting to a cast-able device (tried PS4 and Roku2)

**Comment by PoomSmart** [comment]
YouTube version (15.49) is too old.

**Comment by PoomSmart** [comment]
Need the crash log from when you have the true latest version of YouTube.

**Comment by BitGrub** [comment]
Gotchu https://pastebin.com/TasxtTNi

Though the error is the same

**Comment by PoomSmart** [comment]
@BitGrub Does this build fix your problem?

[com.ps.youpip_0.0.13_iphoneos-arm.deb.zip](https://github.com/PoomSmart/YouPIP/files/6527412/com.ps.youpip_0.0.13_iphoneos-arm.deb.zip)

**Comment by BitGrub** [comment]
Unfortunately with that version of YouPip it crashes about half a second after launching the youtube app.
This time, only CrashReporter made a log (previously I was getting them from Cr4shed)

**Comment by PoomSmart** [comment]
@BitGrub Can you try this one?

[com.ps.youpip_0.0.13_iphoneos-arm.deb.zip](https://github.com/PoomSmart/YouPIP/files/6527800/com.ps.youpip_0.0.13_iphoneos-arm.deb.zip)

**Comment by BitGrub** [comment]
It works! Much appreciated
