### ISSUE TITLE
PiP window crash if the video is previewed before playing (PiP button)

### ISSUE THREAD

**Issue by qnblackcat** [PoomSmart/YouPiP#54]
### Info:
- iOS version: 14.8 (jailbroken with checkra1n/Substitute), 15.x (non jailbroken).
- Device model: all
- Version of YouPiP: 1.7.5
- Version of YouTube: 17.24.4
- **Use PiP Button** is enabled, **Legacy PiP** is disabled

### Step to reproduce the bug:
1. Enable **Use PiP button** in YouPiP.
2. Enable video preview in YouTube's setting > General > **Playback in feeds**
3. Preview any video a few secs before opening it.
4. Use the PiP button to enter PiP mode > go to Home screen > the PiP window will crash.

### Video:
https://user-images.githubusercontent.com/52943116/175798659-db8b1c23-ed52-4d1a-9f58-71a0cec6d707.MOV

### Additional context:
- Doesn't happen with native (auto) PiP.
- Happens on both jailbroken & non-jailbroken version of YouPiP.
- Fixed by restart YouTube, or disable **Playback in feeds** (obviously).

**Comment by PoomSmart** [comment]
Hopefully fixed as of 7db6321a2824756f1ef4163ff3f90b7dfe8168af
