### ISSUE TITLE
Compiling errors (again)

### ISSUE THREAD

**Issue by dayanch96** [PoomSmart/YouPiP#59]
Hi. Getting errors like this. What am I doing wrong? :(

In file included from Tweak.x:2:
In file included from /Users/dan/youpip/Header.h:4:
/Users/user/youpip/AVKit-Header.h:13:30: error: unknown type name 'AVPictureInPictureControllerContentSource'; did you mean 'AVPictureInPictureController'?
@property(nonatomic, retain) AVPictureInPictureControllerContentSource *contentSource API_AVAILABLE(ios(15.0)); // retain -> strong on iOS 15
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                             AVPictureInPictureController

**Comment by PoomSmart** [comment]
Use iOS 15 SDK

**Comment by dayanch96** [comment]
> Use iOS 15 SDK

Problem was on freshly installed xcode.

in xcode > preferences > locations > command line tools were not selected by default. selected it manually and it worked. thank you for your help
