### ISSUE TITLE
Background audio playback always occurs, even when PiP is not active

### ISSUE THREAD

**Issue by SeanTheGleaming** [PoomSmart/YouPiP#64]
When you exit the Youtube app while a video is playing, then background audio playback will be playing whether or not PiP is also playing. I troubleshooted with choicy to determine that this issue is in fact caused by YouPiP entirely independently of other tweaks.

I think that the background playback should be off by default in this tweak, but a toggle could be nice.

**Comment by PoomSmart** [comment]
PiP requires background playback. YouPiP enables PiP and expects background playback to already function. In what real-world cases do you not want background playback?

**Comment by SeanTheGleaming** [comment]
I often will leave the YouTube app to do something else, not planning on
the video I'm watching to continue in background playback. This can often
happen when I'm following an instructional video on youtube, when I could
exit an app to follow along with the video and being able to return to the
youtube app where I left off. I also sometimes just want to quickly exit
the app of put my phone to sleep, and while this can be done by pausing, it
is more convenient without background playback.

To elaborate on what I meant by a toggle or disabling background playback,
I meant only disabling it when PiP is not in use, assuming this is
possible. I do realize that its a possibility that disabling background
playback as described may be impossible, buggy, or otherwise not viable.

**Comment by PoomSmart** [comment]
YouPiP doesn't plan to have this feature.
