### ISSUE TITLE
YouPiP crashes when using YT 17.41.2-Newer

### ISSUE THREAD

**Issue by arichorn** [PoomSmart/YouPiP#76]
## YouPiP
YouPiP was working fine on v17.40.5 but I am gonna guess that YouTube changed something as usual.

## Crash Log
[YouTube-2022-10-17-171448.txt](https://github.com/PoomSmart/YouPiP/files/9804910/YouTube-2022-10-17-171448.txt)

**Comment by PoomSmart** [comment]
Fixed.

**Comment by arichorn** [comment]
thanks! Glad I letted you know ☝️💖
