### ISSUE TITLE
Fake YouTube Version doesn’t work correctly

### ISSUE THREAD

**Issue by arichorn** [PoomSmart/YouPiP#80]
Came here to remind you that Fake YouTube Version doesn’t work with the current version of YouTube.
Right now of using it, Fake YouTube Version doesn’t effect the UI, Version Number & anything else that it worked with. If there’s no fix then it’s alright. 👍

**Comment by arichorn** [comment]
Alright I’ll show you below

**Comment by arichorn** [comment]
YouTube Fake Version no longer changes to the old ui when toggled on
![2B5C0B5A-B954-408D-BA1C-C091C6893E90](https://user-images.githubusercontent.com/78001398/205081230-91187613-c011-4340-bafc-94a0c745f70a.jpeg)
This is what it looks like when Fake YouTube Version is on or even off. which is one of the reasons why I downgrade the app version.

next issue is the UIColor methods used around the app. I Usually use Fake YouTube Version to remove this type of change. Don’t know why YouTube changed the UIColor methods but makes it really hard to change as of today.

third issue is that the tweak uYou 2.1 will no longer show buttons on the in the video player settings menu, under the video player & and the 3 dots in the app. usually Fake YouTube Version fixes that problem but highly unlikely now.
![D0FC3EBC-F78D-4A18-BC27-FC4D55AFE059](https://user-images.githubusercontent.com/78001398/205083128-d4c6ad1d-4cac-4dd5-bf54-2d4a2794924c.jpeg)
But you can still show in the Video Player Overlay. That’s it.

That pretty much wraps up my explanation on why Fake YouTube Version is not working.

**Comment by arichorn** [comment]
Sorry that I changed the title and PoomSmart hope things help out YouPiP with what I said about it. Also I’m unable to re-open this so it’s gonna be hard for you to notice

**Comment by PoomSmart** [comment]
Reopened for tracking.

**Comment by arichorn** [comment]
Also YouTube really loves to force users to use their new color for texts
‘_CachedColor‘ & ‘dynamicLabelColor‘ I found these in the latest version using FLEX Menu, I really hoped that it should’ve reverted with YouTube Fake Version but I know it doesn’t effect all the app elements

**Comment by PoomSmart** [comment]
The old/new video layout issue fixed in 1.7.17

Irrelevant discussions will not be tolerated in the future.
