### ISSUE TITLE
ipad 12.5.7 can't play video

### ISSUE THREAD

**Issue by H4NJ1N** [PoomSmart/YouPiP#87]
I'm in ipad os 12.5.7
youtube 17.39.4 (it's my highest version) and i paid youtube premium
youpip 1.7.19-2 (because 1.7.20 not working - can't able tweak)

When i apply twick and play the video, the app stops and shuts down
It's similar to this closed problem
https://github.com/PoomSmart/YouPiP/issues/41

Maybe it worked on youtube 17.20.3 youpip 1.7.2 but something got twisted and came to a higher version. And it's the same situation now. Can you save me?

**Comment by H4NJ1N** [comment]
[텍스트-11E27B314790-1.txt](https://github.com/PoomSmart/YouPiP/files/12266867/-11E27B314790-1.txt)

**Comment by H4NJ1N** [comment]
1. not able is working
https://github.com/PoomSmart/YouPiP/assets/72609275/da01d3b8-0b02-4aeb-900b-09a8142d8107

2. able is not working TnT
https://github.com/PoomSmart/YouPiP/assets/72609275/52212a7a-7013-47e6-978d-966d1486ccf5

**Comment by PoomSmart** [comment]
From my testing, iOS 12.5.7 jailbroken with Chimera will work, but checkra1n won't.

I concluded this to be a jailbreak-specific issue.
