### ISSUE TITLE
Legacy PiP no longer works on latest version

### ISSUE THREAD

**Issue by Yehh22** [PoomSmart/YouPiP#90]
The last working version if 18.40.01. After updating to newer version, Legacy PiP no longer works. Tapping on PiP icon on the video or on tab bar does nothing. The new PiP works but the bug #29 still present. Yes I can downgrade Youtube but it's annoying having to downgrade everyday, because App store auto update it

Another issue is video keeps pausing everytime I seek the video. Idk what version Youtube implemented new UI preview

**Comment by PoomSmart** [comment]
Fixed in 1.7.22
