### ISSUE TITLE
Mysterious combo of YouPIP

### ISSUE THREAD

**Issue by CySxL** [PoomSmart/YouPiP#94]
YouPIP version: 1.8.1

When you inject YouPIP to YouTube 19.01.1, and sideload to another device on iOS 14 (I know it's kinda dumb but some people prefer to use it in this way lol.), YouPIP stops working on "streaming" video.
![image](https://github.com/PoomSmart/YouPiP/assets/15531137/aea3cb87-1362-4e3d-b8c4-084c5373ef3b)

So the combo is:
1. Injected YT IPA with YouPIP
2. Install the IPA on iOS 14
3. Play a streaming video.

**Comment by PoomSmart** [comment]
But does it work if YT app is from App Store? And does it work with older version of YT?

**Comment by CySxL** [comment]
> But does it work if YT app is from App Store? And does it work with older version of YT?

Yes, it works with App Store YT app on every builds. And it also works on injected YT IPA on iOS15/16.

So only "injected IPA" + "iOS 14" + "Streaming" won't work.
