### ISSUE TITLE
Legacy PiP Can't disable

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [PoomSmart/YouPiP#95]
As long as YouPiP is enabled, Legacy PiP cannot be disable. Unless YouPiP is also disabled.

**Comment by PoomSmart** [comment]
@xiangfeidexiaohuo iOS version?

**Comment by xiangfeidexiaohuo** [comment]
> @xiangfeidexiaohuo iOS version?

iOS 15.1.1  
I have tried almost every version of YouTube recently and cannot turn off Legacy PiP alone.
And the PIP button all crashes.

**Comment by PoomSmart** [comment]
@xiangfeidexiaohuo Crash log?

**Comment by PoomSmart** [comment]
Stale
